# Generated by Django 3.2.8 on 2021-10-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211020_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advert',
            new_name='Footer',
        ),
    ]
